AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: s3://lambda-artifacts-c140765f99dbd1f8/651625e57a864e19044106944510ecb1
      Description: Call the AWS Lambda API
      Timeout: 10
      Policies:
      - AWSLambdaSQSQueueExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
      - Ref: libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-python-lib
      Description: Dependencies for the blank-python sample app.
      ContentUri: s3://lambda-artifacts-c140765f99dbd1f8/f08ec53851f0c8a71a0f2dcdadeb5c71
      CompatibleRuntimes:
      - python3.8
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      VisibilityTimeout: 120
  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn:
        Fn::GetAtt:
        - MyQueue
        - Arn
      FunctionName:
        Fn::GetAtt:
        - LambdaFunction
        - Arn
